FROM rockylinux/rockylinux:8.4

RUN dnf update -y && \
    dnf install -y \
        automake \
        cmake \
        curl \
        git \
        libcurl-devel \
        jansson-devel \
        libtool

