FROM rockylinux/rockylinux:8.4

RUN dnf update -y && \
    dnf install -y \
      epel-release && \
    dnf install -y \
      automake \
      curl-devel \
      git \
      jansson-devel \
      libtool \
      libjwt-devel \
      make

