name: lint
on: pull_request

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container: ghcr.io/hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - run: hadolint **/**/Dockerfile
